routes/web.php
<?php

use App\Http\Controllers\Admin\GroupController;
use App\Http\Controllers\Admin\HVI\AllHome\MetroController;
use App\Http\Controllers\Admin\HVI\AllHome\ZipCodeController;
use App\Http\Controllers\Admin\HVI\HomeValueIndexController;
use App\Http\Controllers\Admin\HVIAllHomeMetroController;
use App\Http\Controllers\Admin\iValuationController as AdminiValuationController;
use App\Http\Controllers\Admin\PropertyController;
use App\Http\Controllers\Admin\Voyager\UserController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Auth\UserLoginController;
use App\Http\Controllers\CrawController;
use App\Http\Controllers\iValuationController;
use App\Http\Controllers\User\Auth\EstimateController;
use App\Http\Controllers\User\Auth\ProfileController;
use App\Http\Controllers\User\HomeController;
use App\Http\Controllers\User\SearchController;
use Goutte\Client;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get(
        's', function (\Illuminate\Http\Request $request) {
    $site = 'https://www.zillow.com/search/GetSearchPageState.htm?searchQueryState={"pagination":{},"usersSearchTerm":"29014 42nd Ave S Auburn, WA 98001","mapBounds":{"west":-122.28265732526779,"east":-122.27935284376144,"south":47.34055668528492,"north":47.34151998871271},"isMapVisible":true,"filterState":{"sortSelection":{"value":"globalrelevanceex"},"isAllHomes":{"value":true}},"isListVisible":true,"mapZoom":18}&wants={"cat1":["listResults","mapResults"],"cat2":["total"]}&requestId=3';

    $crawler = \Illuminate\Support\Facades\Http::get($site);
//    $client = new Client();
//    $crawler = $client->request('GET', $site);
    dd($crawler->collect()->toArray());
}
);
Route::group(['prefix' => 'craw'], function () {
    Route::get('category', [CrawController::class, 'category']);
    Route::get('sub-category/{code}', [CrawController::class, 'subCategory']);
    Route::get('get-product/{code}', [CrawController::class, 'getProductByCategory']);
});
Route::group(['prefix' => 'ivaluation'], function () {
    Route::get('step-1', [iValuationController::class, 'category']);
});
Route::get('/', 'App\Http\Controllers\User\HomeController@index')->name('home');
Route::post('/contact', 'App\Http\Controllers\User\HomeController@contact')->name('contact');
Route::get('/direct', 'App\Http\Controllers\User\HomeController@direct')->name('direct');
Route::get('/about-us', 'App\Http\Controllers\User\HomeController@getListTeams')->name('aboutus');
Route::get('blogs/{title}/{id}', [HomeController::class, 'blogs'])->name('blogs');
Route::get('/our-work', 'App\Http\Controllers\User\HomeController@getListProjects')->name('project');
Route::get('/scope-of-work/{id}', 'App\Http\Controllers\User\HomeController@getProperty')->name('property.get');
Route::get(
        'estimate', function () {
    return view('landingpage.estimate.index');
}
);
Route::post('estimate', [HomeController::class, 'estimate'])->name('estimate');
Route::put('update-property/{id}', [HomeController::class, 'updateProperty'])->name('updateProperty');

Route::put('update-property-image/{id}', [HomeController::class, 'updatePropertyImage'])->name('updatePropertyImage');
Route::post('add-property-image/{id}', [HomeController::class, 'addPropertyImage'])->name('addPropertyImage');
Route::get('delete-property-image/{id}', [HomeController::class, 'deletePropertyImage'])->name('deletePropertyImage');

Route::group(['prefix' => 'ivaluation', 'as' => 'ivaluation.'], function () {
    Route::get('/', function () {
        return view('landingpage.valuation.index');
    })->name('ivaluation');
//    Route::get('step-1', [iValuationController::class, 'step1'])
//            ->name('step1');
//    Route::get('step-2', [iValuationController::class, 'step2'])
//            ->name('step2');
    Route::get('calculate', [iValuationController::class, 'calculate'])->name('calculate');
    Route::get('result/{id}', [iValuationController::class, 'result'])->name('result');

});


Route::prefix('')->group(
        function () {
            Route::get('register', [RegisterController::class, 'showRegistrationForm'])
                    ->name('user.register');
            Route::post('register', [RegisterController::class, 'register'])
                    ->name('user.register');
            Route::get('login', [UserLoginController::class, 'showLoginForm'])->name('user.login');
            Route::post('login', [UserLoginController::class, 'login'])->name('user.login.submit');
            Route::get('logout', [UserLoginController::class, 'logout'])->name('user.logout');
            Route::post('logout', [UserLoginController::class, 'logout'])->name('user.logout.submit');
        }
);

Route::group(['middleware' => ['customer']], function () {
    Route::group(
            ['prefix' => 'profile'], function () {
        Route::get('/', [ProfileController::class, 'index'])->name('user.profile');
        Route::post('update-profile', [ProfileController::class, 'update'])->name(
                'user.profile.update'
        );
        Route::post('update-password', [ProfileController::class, 'update'])->name(
                'user.password.update'
        );
    });
    Route::get('list-estimate', [EstimateController::class, 'index'])->name('user.list-estimate');
    Route::get('estimate/{id}', [EstimateController::class, 'walkProperty'])
            ->name('user.walkProperty');
    Route::get('walked/{id}', [EstimateController::class, 'walkedProperty'])
            ->name('user.walkedProperty');
    Route::get('settings', [ProfileController::class, 'logout'])->name('user.settings');
});
//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('search', [SearchController::class, 'index'])
        ->name('search');

Route::group(
        ['prefix' => 'admin', 'middleware' => ['auth']], function () {
    Voyager::routes();

    Route::group(
            [], function () {
        Route::resource('gift', PropertyController::class)->names('admin.gift');

        Route::get('hvi', [MetroController::class, 'index'])->name('admin.hvi');
        Route::get('ivaluation', [AdminiValuationController::class, 'index'])->name('admin.ivaluation');

        Route::put('update-property-image/{id}', [PropertyController::class, 'updatePropertyImage'])
                ->name('voyager.property.updatePropertyImage');
        Route::post('add-property-image/{id}', [PropertyController::class, 'addPropertyImage'])
                ->name('voyager.property.addPropertyImage');
        Route::get('delete-property-image/{id}', [PropertyController::class, 'deletePropertyImage'])
                ->name('voyager.property.deletePropertyImage');

        Route::post('property/create-walk/{id}', [PropertyController::class, 'createWalk'])
                ->name('voyager.property.createWalk');

        Route::get('property/walked/{id}', [PropertyController::class, 'walked'])
                ->name('voyager.property.walked');
        Route::get('property/export/{id}', [PropertyController::class, 'export'])
                ->name('voyager.property.export');

        Route::get('home-value-index-all-home-metro', [MetroController::class, 'index'])
                ->name('admin.hvi.allhome.metro.index');

        Route::get('home-value-index-all-home-zipcode', [ZipCodeController::class, 'index'])
                ->name('admin.hvi.allhome.zipcode.index');
        Route::group(
                ['prefix' => 'home-value-index', 'as' => 'admin.hvi.'], function () {
            Route::group(
                    ['prefix' => 'all-home', 'as' => 'allhome.'], function () {
                Route::get('metro/view/{id}', [MetroController::class, 'view'])
                        ->name('metro.view');
                Route::post('metro/import', [MetroController::class, 'import'])
                        ->name('metro.import');


                Route::get('zipcode/view/{id}', [ZipCodeController::class, 'view'])
                        ->name('zipcode.view');
                Route::post('zipcode/import', [ZipCodeController::class, 'import'])
                        ->name('zipcode.import');
            }
            );
        }
        );

//    Route::resource('group', GroupController::class);

        Route::get('profile', [UserController::class, 'profile'])
                ->name('voyager.profile');
    }
    );
}
);

resources/views/landingpage/valuation/index.blade.php
@extends('landingpage.app')
@section('title', 'iValuation')

@section('content')

    {{--    @include('landingpage.valuation.sale-offer')--}}
    <!-- ======= About Section ======= -->
    <section class=" bg-blue text-white">
        <div class="row content" data-aos="fade-up">
            <div class="col-md-6 offset-md-3 col-12 text-center my-3" id="heroCarousel">
                <h1>
                    iValuation Tools
                </h1>
            @include('landingpage.valuation.search')
            </div>
        </div>

    </section>
    <section id="about" class="container about bg-white mt-5">
        <div class="container">

            <div class="section-title text-center" data-aos="zoom-out">
                <h3 class="text-blue mb-5">Welcome To A New Era of Instant <br/> Home Valuation.</h3>
                <span>Real-time and convenient Home Value Estimates.</span>
            </div>

            <div class="row content mt-4" data-aos="fade-up">
                <div class="col-lg-10 col-12 offset-lg-1">
                    <div class="testimonial-item text-justify text-center">
                        <ul>
                            <li>
                                <span class="d-block"><i
                                        class="bx bxs-quote-left quote-icon-left position-relative"></i> Gone are the days when you have to reply on real estate agents and appraisers to determine the </span>
                                <span class="d-block ml-2"> fair market value of your home. It's 2021 and the real estate industry has advanced to enable you </span>
                                <span class="d-block">to check your home value online in seconds. <i
                                        class="bx bxs-quote-right quote-icon-right position-relative"></i></span>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-12 col-12 text-center my-4">
                    <a href="{{ route('ivaluation.ivaluation') }}" class="btn-outline-blue">
                        Start NOW <i
                            class='bx bxs-chevron-right ml-3'></i></a>
                </div>
            </div>
        </div>
    </section><!-- End About Section -->

    <!-- ======= Using======= -->
    <section class="container why-us bg-blue mt-5">
        <div class="container pb-2">
            <div class="row content" data-aos="fade-up">

                <div class="col-lg-12 col-12 mb-5">
                    <div class="text-center text-white">
                        <span class="badge badge-pill badge-primary py-2 px-3"><strong class="h5">Using</strong></span>
                    </div>
                </div>


                <div class="col-lg-4 col-12 text-white mb-5">
                    <div class=" text-white">
                        <span class="fa fa-check-circle text-primary fa-lg mr-2"></span>
                        <strong class="h4">Market trends</strong>
                    </div>
                </div>

                <div class="col-lg-4 col-12 text-white mb-4">
                    <div class=" text-white">
                        <span class="fa fa-check-circle text-primary fa-lg mr-2"></span>
                        <strong class="h4">Advanced algorithms</strong>
                    </div>
                </div>

                <div class="col-lg-4 col-12 text-white mb-4">
                    <div class=" text-white">
                        <span class="fa fa-check-circle text-primary fa-lg mr-2"></span>
                        <strong class="h4">Industry insights</strong>
                    </div>
                </div>

                <div class="col-lg-8 col-12 text-white mb-4">
                    <div class=" text-white">
                        <span class="fa fa-check-circle text-primary fa-lg mr-2"></span>
                        <strong class="h4">Estimates from local & national iValuation</strong>
                    </div>
                </div>

            </div>
        </div>
    </section><!-- End Why Us Section -->

    <section class="container bg-blue p-0">
        <div class="row content bg-primary" data-aos="fade-down">
            <div class="col-12 text-white p-4 text-center">
                We're now able to provide you with the current market value of your home using <br/> just your house
                address.
            </div>
        </div>
    </section>

    <section id="about" class="container about bg-white">
        <div class="container">
            <div class="section-title text-center" data-aos="zoom-out">
                <h3 class="text-blue">How our <br/> Home Value Estimator Works.</h3>
                <span>Introducing our iValuation proprietary online Home Value Estimator tool.</span>
            </div>
            <div class="col-lg-12 col-12 text-center my-3">
                <a href="{{ route('ivaluation.ivaluation') }}" class="btn-blue">Launch Tool</a>
            </div>
            <div class="col-lg-10 offset-md-1 col-12 text-center my-5 bg-light p-5">
                <div class="row">
                    <div class="col-lg-2 col-12 text-left">
                        <div class="circle-step mx-auto mb-2">1</div>
                    </div>
                    <div class="col-lg-6 col-12 text-justify">
                        <h3 class="text-primary">You Enter You Home <br/> Address</h3>
                        <p>To provide ypu with a free home value estimate, we <br/> begin by pulling market value data
                            in your area and <br/> accessing neighborhood statistics.</p>
                    </div>
                    <div class="col-lg-4 col-12 img-step d-none d-md-block">
                        <img src="/assets/img/global.png" alt="" class="img-fluid position-absolute"/>
                    </div>
                </div>
            </div>
            <br/>
            <div class="col-lg-10 offset-md-1 col-12 text-center my-5 bg-light p-5">
                <div class="row">
                    <div class="col-lg-4 col-12 img-step d-none d-md-block">
                        <img src="/assets/img/computer.png" alt="" class="img-fluid position-absolute"/>
                    </div>
                    <div class="col-lg-6 col-12 text-right">
                        <h3 class="text-primary">We Pull Real-Time <br/> Industry Data</h3>
                        <p>Proprietary algorithms, real estate insights,
                            and access to big data from local and national iValuation enables us to present you with the
                            most accurate home value estimate in seconds.</p>
                    </div>
                    <div class="col-lg-2 col-12 text-left">
                        <div class="circle-step mx-auto mb-2">2</div>
                    </div>
                </div>
            </div>
            <br/>
            <div class="col-lg-10 offset-md-1 col-12 text-center my-5 bg-light p-5">
                <div class="row">
                    <div class="col-lg-2 col-12 text-left">
                        <div class="circle-step mx-auto mb-2">3</div>
                    </div>
                    <div class="col-lg-6 col-12 text-justify">
                        <h3 class="text-primary">You Get Your Home <br/> Value Estimate</h3>
                        <p>Find out what your home is worth based on fair market value assessments and see what iBuyers
                            would be willing to pay for your hourse.
                            If you choose to request a cash offer.</p>
                    </div>
                    <div class="col-lg-4 col-12 img-step d-none d-md-block">
                        <img src="/assets/img/invoice.png" alt="" class="img-fluid position-absolute"/>
                    </div>
                </div>
            </div>
        </div>
    </section><!-- End About Section -->

    <!-- ======= Using======= -->
    <section class="container why-us bg-blue">
        <div class="row content" data-aos="fade-up">
            <div class="col-lg-12 col-12 ">
                <div class="section-title text-center text-white" data-aos="zoom-out">
                    <h3 class="mb-4">Traditional Home Valuation <br/> vs. New Age Home iValuation</h3>
                    <span>Discover the difference between traditional home valuation and iBuyer home valuation.</span>
                </div>
            </div>
        </div>
    </section>

    <section class="container bg-white">
        <div class="row content" data-aos="fade-up">
            <div class="col-lg-12 col-12 text-center mb-4">
                <span>The problem with this old-school model is twofold</span>
            </div>
            <div class="d-lg-flex d-block">
                <div class="col-lg-6 col-12">
                    <div class="p-4 px-5 bg-light h-100 rounded">
                        <div class="row">
                            <div class="col-lg-1 col-md-1 col-12 p-0 text-sm-right">
                                <i class="fas fa-times-circle text-danger fa-2x"></i>
                            </div>
                            <div class="col-lg-11 col-md-11 col-12">
                                <h3>It's subjective</h3>
                                <p class="text-justify">Realtors (who aer trying to win your business) come to see your
                                    house
                                    in person and then share with you what they think you could get for it</p>
                            </div>
                        </div>
                    </div>
                </div>
                <br/>
                <div class="col-lg-6 col-12">
                    <div class="p-4 px-5 bg-light h-100 rounded">
                        <div class="row">
                            <div class="col-lg-1 col-md-1 col-12 p-0 text-sm-right">
                                <i class="fas fa-times-circle text-danger fa-2x"></i>
                            </div>
                            <div class="col-lg-11 col-md-11 col-12">
                                <h3>Realtor tend to inflate the amount your home</h3>
                                <p class="text-justify">It's worth to win your business and because they hope to make a
                                    bigger commission on the sale.)</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row" data-aos="fade-up">
            <div class="container bg-primary m-3 rounded p-4">
                <div class="col-lg-12 col-12">
                    <div class="section-title text-center text-white" data-aos="zoom-out">
                        <h2 class="mb-4">Curious what your home is worth?</h2>
                        <span>Get your free online estimate in seconds using our <br/> Home Value Estimator tool.</span>
                    </div>
                </div>
                <div class="col-lg-12 col-12 text-center my-2">
                    <a href="{{ route('ivaluation.ivaluation') }}" class="btn-blue">Check Home Value</a>
                </div>
            </div>
        </div>
    </section><!-- End Why Us Section -->


    <!-- </main>End #main -->
@endsection

resources/views/landingpage/valuation/search.blade.php
    {{--                <form action="{{ route('ivaluation.step1') }}" method="get">--}}
    <div class="input-group search mt-lg-3 mt-0 w-100">
        <div class="input-group-prepend">
                            <span class="input-group-text bg-white no-border">
                                <i class="fas fa-map-marker-alt"></i>
                            </span>
        </div>
        <input required autocomplete="off" type="text" class="form-control no-border"
               value="{{ Request::input('address') }}"
               placeholder="Enter your home address"
               id="search" name="search">
        {{--                        <div class="input-group-append">--}}
        {{--                            <button type="submit" class="input-group-text text-blue bg-white no-border">--}}
        {{--                                Get your home value--}}
        {{--                            </button>--}}
        {{--                        </div>--}}
    </div>
    {{--                </form>--}}
    <div class="row">
        <div class="search autocomplete-items mr-2 px-2" style="
    width: 100%;
    position: relative;
    height: auto;
" align="left">

        </div>
    </div>
@push('script')
    <script>
        var timeout = null;
        $('#search').keyup(function () {
            clearTimeout(timeout);
            timeout = setTimeout(function () {
                $.ajax({
                    type: 'GET',
                    dataType: 'json',
                    data: {search:$('#search').val()},
                    url: '{{ route('api.map.search') }}',
                    success: function (result) {
                        var items  ='';
                        if(result.status=='success') {
                            $.each(result.data, function (key,value){
                                items+=' <a href="{{ route('ivaluation.calculate') }}?address='+key+'"><div class="p-3">'+ value +'</div></a>';
                            })
                        }
                        $('.autocomplete-items').html(items)
                    }
                });
            }, 500);
        });

    </script>
@endpush

resources/views/landingpage/valuation/step2.blade.php
@extends('landingpage.app')
@section('title', 'iValuation')

@section('content')
    <div class="text-center py-4">
        <h1>
            Property Information
        </h1>
        <p>
            {{ Request::input('address') }}
        </p>
    </div>
    <div class="container ">
        <div class="row">
            <div class="card col-12 col-md-10 offset-md-1">
                <div class=" card-body">
                    {!! Form::open(['url'=>route('ivaluation.calculate')]) !!}
                    <input type="hidden" name="address" value="{{ Request::input('address') }}">
                    <div class="row">
                        <div class="col-lg-6 col-12">
                            <div class="form-group">
                                <label class="label-require" >Main Square FT </label>
                                <input type="number" required class="form-control" name="main_square_ft"
                                       value="{{ old('main_square_ft') }}"
                                       id="main_square_ft" placeholder="Main Square FT"
                                       oninput="this.value = this.value.replace(/[^0-9.]/g, '');"
                                       data-rule="regexp:^((\d+\.\d{1,2})|(\d+)|(\.\d{1,2}))$"
                                       data-msg="Please enter a valid Main Square FT" maxlength="10"/>
                                <div class="validate"></div>
                            </div>
                        </div>
                        <div class="col-lg-6 col-12">
                            <div class="form-group">
                                <label class="label-require">Number Bedrooms</label>
                                <input type="number" required class="form-control" name="number_bedrooms" id="number_bedrooms"
                                       placeholder="Number Bedrooms" data-rule="required"
                                       oninput="this.value = this.value.replace(/[^0-9]/g, '');" maxlength="3"
                                       data-msg="Please enter number bedrooms"/>
                                <div class="validate"></div>
                            </div>
                        </div>
                        <div class=" col-12">
                            <div class="form-group">
                                <label class="label-require">Your home type</label>
                                {!! Form::select('home_type',\App\Models\iValuation::home_type(),'',['class'=>'form-control ']) !!}
                            </div>
                        </div>
                        @if(\Auth::guest() || (\Auth::check() && !\Auth::user()->hasRole('Customer')))
                            <div class="col-12 ">
                                <h3>
                                    Your information
                                </h3>
                            </div>
                                <div class="col-lg-4 col-12">
                                    <div class="form-group">
                                        <label class="label-require">Email</label>
                                        <input type="email" required name="email" class="form-control">
                                    </div>
                                </div>
                                <div class="col-lg-4 col-12">
                                    <div class="form-group">
                                        <label class="label-require">Name</label>
                                        <input type="text" maxlength="255" required name="name" class="form-control">
                                    </div>
                                </div>
                                <div class="col-lg-4 col-12">
                                    <div class="form-group">
                                        <label class="label-require">Phone</label>
                                        <input type="number" required name="phone" class="form-control">
                                    </div>
                                </div>
                        @endif
                        <div class=" col-12 text-center">
                            <button type="submit" class="btn btn-primary">
                                Get iValuation
                            </button>
                        </div>
                    </div>
                    <input type="hidden" name="lat" id="lat">
                    <input type="hidden" name="lng" id="lng">
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection
@push('script')
    <script>
        geocoder = new google.maps.Geocoder();
        geocoder.geocode({
            'address': "{{ Request::input('address') }}"
        }, function(results, status) {
            if (status == google.maps.GeocoderStatus.OK) {
                $('#lat').val(results[0].geometry.location.lat())
                $('#lng').val( results[0].geometry.location.lng())
            }
        })
    </script>
@endpush

resources/views/landingpage/valuation/valuation.blade.php
@extends('landingpage.app')
@section('title', 'iValuation')

@section('content')
    <div class="text-center py-4">
        <h1>
            iValuation Result
        </h1>
        <p>
            {{ Request::input('address') }}
        </p>
    </div>
    <div class="container ">
        <div class="row">
            <div class="card col-12 col-md-6 offset-md-3">
                <div class=" card-body">
                    <div class="row text-center">
                        <div class="col-12 mb-2" >
                            {{ $valuation->address }}
                        </div>
                        <p class="col-6">
                            <b> Main Square FT:</b> {{ number_format($valuation->main_square_ft) }}
                        </p>
                        <p class="col-6">
                            <b> Number Bedrooms:</b> {{ number_format($valuation->bedroom) }}
                        </p>
                        <p class="col-12">
                            <b> Home type:</b> {{ \App\Models\iValuation::home_type()[$valuation->home_type] }}
                        </p>
                        <p class="col-12">
                            <b class="h1 text-blue"> Home Valuation:</b>
                            <br>
                            <b class="h1">
                                {{ formatCurrency($valuation->valuation) }}
                            </b>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('script')
@endpush